### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by mrc4tt** [CounterStrafe/docker-adminafk#1]
Hi,

I will hear, about it's possible to install this on "remote" server eg: VPS/Dedicated Server?

Since readme is not updated, so it's unsure, what needs to be *edited* for getting it to work on HTTP://IP-Server OR HTTP://domainhere

**Comment by eoswald** [comment]
Yes, this does work on a remote server. You need to replace the `EBOT_IP` in the docker-compose.yml:
https://github.com/CounterStrafe/docker-adminafk/blob/master/docker-compose.yml#L68

You need to replace the `server_name` in the nginx app.conf:
https://github.com/CounterStrafe/docker-adminafk/blob/master/data/nginx/app.conf

And you need to adjust these regexes in the Let's Encrypt script:
https://github.com/CounterStrafe/docker-adminafk/blob/master/deploy.sh#L3-L4

We stopped using this service so keep in mind this repo is no longer maintained or supported. Everything should be working though.
